### ISSUE TITLE
Ability to specify input image by name

### ISSUE THREAD

**Issue by CamDavidsonPilon** [OctoPrint/CustoPiZer#15]
Maybe a support ask / documentation ask: is it possible to specify the file name of the input image, instead of assuming `input.img`?

**Comment by foosel** [comment]
When calling the script, the Docker container or the GitHub Action?

- Script: First parameter
- Docker container: First parameter to command
- Action: No, currently not. Could be added however.

**Comment by CamDavidsonPilon** [comment]
Hi @foosel, I was running Custopizer locally to generate images, but I since moved to GH actions (heavily inspired by Ocotoprint's GH actions), and actually I don't need this anymore. Thanks!
