### ISSUE TITLE
Setting up environment to build custom image

### ISSUE THREAD

**Issue by jpapiez** [OctoPrint/CustoPiZer#23]
Hello. I'm fairly new to Linux. Running ubuntu 20.04 and trying to build a custom raspberry pi image, starting from the latest octopi image. I have configured everything I want in my custom image and when I run the docker command I get the following error that I'm note sure how to work around:

```
update-binfmts: warning: qemu-arm already enabled in kernel.
mount: /proc/sys/fs/binfmt_misc: binfmt_misc already mounted on /proc/sys/fs/binfmt_misc.
Running /CustoPiZer/start_chroot_script in chroot...
Building on non-ARM device a armv7l system, using qemu-arm-static
qemu-arm-static: /bin/bash: Invalid ELF image for this architecture

```

**Comment by CamDavidsonPilon** [comment]
You may be using the wrong config. Does this help? https://github.com/OctoPrint/CustoPiZer/issues/21

**Comment by jpapiez** [comment]
That was definitely the case. Thanks!
